# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvtjt7-FmhnU-bPk5PjD8SPtFGUHZrcc
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


mu_0 = 4 * np.pi * 1e-7
I = 1
R = 1
theta = np.linspace(0, 2 * np.pi, 100)

x = R * np.cos(theta)
y = R * np.sin(theta)
z = np.zeros_like(x)

Bx = -mu_0 * I * y / (2 * np.pi * (x*x + y*y)**(3/2))
By = mu_0 * I * x / (2 * np.pi * (x*x + y*y)**(3/2))
Bz = np.zeros_like(Bx)
magnitude = np.sqrt(Bx**2 + By**2 + Bz**2)
Bx /= magnitude
By /= magnitude
Bz /= magnitude

fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

ax.quiver(x, y, z, Bx, By, Bz, length=0.1, color='r', label='Magnit maydonining yo‘nalishi')

ax.set_title("3D Magnit Maydoni Tokli Zanjirdagi Ta'siri")
ax.set_xlabel('X koordinata (m)')
ax.set_ylabel('Y koordinata (m)')
ax.set_zlabel('Z koordinata (m)')

ax.set_aspect('auto')
ax.legend()

plt.show()